### ISSUE TITLE
Lazy Module Loading enabled but Modules still imported from AppModule

### ISSUE THREAD

**Issue by rogargon** [ardiadrianadri/good-practices-angular#24]
Regarding Step 3 and lazy module loading:
https://github.com/ardiadrianadri/good-practices-angular/blob/e0038d6e407604685aacf5067868b655d99adfdc/src/app/app.module.ts#L19

And as detailed in the Angular documentation, shouldn't the modules being loaded lazily be removed from the AppModule imports?

From https://angular.io/guide/router#lazy-loading-route-configuration:

"Take the final step and detach the admin feature set from the main application. The root AppModule must neither load nor reference the AdminModule or its files.

In app.module.ts, remove the AdminModule import statement from the top of the file and remove the AdminModule from the NgModule's imports array."

**Comment by ardiadrianadri** [comment]
Hello @rogargon:

 You are absolutely right. If the modules are added in the AppModule there is not any lazy loading because they are loaded at the beginning when the AppModule starts. That was my mistake; when I did the refactor from the Step 2 I've forgotten this part. 

 I can bet the same error are in the next steps :P 

Thank you very much for your collaboration.
